---
apiVersion: v2
name: frp-operator
description: Expose your service in Kubernetes to the Internet with open source FRP!
version: 1.6.0
appVersion: 0.8.0
type: application
home: https://github.com/librepod/frp-operator

maintainers:
- name: LibrePod
  url: https://github.com/librepod
